package com.studerw.tda.model.account;

public enum ComplexOrderStrategyType {
  NONE,
  COVERED,
  VERTICAL,
  BACK_RATIO,
  CALENDAR,
  DIAGONAL,
  STRADDLE,
  STRANGLE,
  COLLAR_SYNTHETIC,
  BUTTERFLY,
  CONDOR,
  IRON_CONDOR,
  VERTICAL_ROLL,
  COLLAR_WITH_STOCK,
  DOUBLE_DIAGONAL,
  UNBALANCED_BUTTERFLY,
  UNBALANCED_CONDOR,
  UNBALANCED_IRON_CONDOR,
  UNBALANCED_VERTICAL_ROLL,
  CUSTOM
}


